### ISSUE TITLE
Spatial Control

### ISSUE THREAD

**Issue by InstantWindy** [sunshineatnoon/PytorchWCT#10]
Did you implement the Spatial Control?

**Comment by sunshineatnoon** [comment]
It's included in this [project](https://github.com/NVIDIA/FastPhotoStyle). If you don't do the second propagation process, then it's just a style transfer with spatial control.

**Comment by InstantWindy** [comment]
I just want to implement a background that only replaces the content image, not replacing the other

**Comment by sunshineatnoon** [comment]
What do you mean by only replaces the content image?

**Comment by lisa92203** [comment]
I think @InstantWindy meant masking.
