### ISSUE TITLE
Hi, I got a model load error

### ISSUE THREAD

**Issue by winwinJJiang** [sunshineatnoon/PytorchWCT#13]
No such file or directory: 'models/vgg_normalised_conv1_1.t7'.

I guess there should be that file in the models folder. But it is not.

Thanks

**Comment by sunshineatnoon** [comment]
Pretrained encoder and decoder can be found [here](https://drive.google.com/file/d/1REga1z1rKezQtBebIZ86_iNR-mxum-KB/view?usp=sharing), please download and uncompress them under `models/`

**Comment by winwinJJiang** [comment]
Thanks very much!

**Comment by winwinJJiang** [comment]
@sunshineatnoon  Just wondering when you will make your linear transfer paper code available?
Great work!!!

**Comment by sunshineatnoon** [comment]
@winwinJJiang Thanks. Code is available upon publication :)

**Comment by winwinJJiang** [comment]
Will you submit to CVPR?

**Comment by Jamie-Cheung** [comment]
> Pretrained encoder and decoder can be found [here](https://drive.google.com/file/d/1REga1z1rKezQtBebIZ86_iNR-mxum-KB/view?usp=sharing), please download and uncompress them under `models/`

Can you give a new link?
