### ISSUE TITLE
Is this because of higher version of pytorch?

### ISSUE THREAD

**Issue by shirishr** [sunshineatnoon/PytorchWCT#14]
I run into this error:

No module named 'torch.utils.serialization'

Traceback (most recent call last):
  File "WCT.py", line 9, in <module>
    from util import *
  File "/home/sam/Documents/ComputerVision/styleTransfer/PytorchWCT/util.py", line 3, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'

**Comment by sunshineatnoon** [comment]
No, I tried `from torch.utils.serialization import load_lua
` for `torch==0.5.0a0+9b0cece` and the module can be imported. Could you try to import this module in your terminal? If you cannot import it, maybe your pytorch is not installed correctly.

**Comment by shirishr** [comment]
It is because of torch==v1.0rc1.
