### ISSUE TITLE
Not running under torch 1.0.0

### ISSUE THREAD

**Issue by victorkitov** [sunshineatnoon/PytorchWCT#17]
When I run `python WCT.py --cuda`, I get an error:

```
Traceback (most recent call last):
  File "WCT.py", line 9, in <module>
    from util import *
  File "/home/apogentus/Desktop/Projects/Experiments/Style_transfer/Not_mine_ST/PytorchWCT-master/util.py", line 3, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'
```

I use pytorch v.1.0.0, ubuntu 18.04, python 3.6.8. From this [discussion](https://github.com/pytorch/pytorch/issues/15307) it follows that load_lua is no longer supported for torch 1.0.0. Could you please make your code compatible with the current version of pytorch or recommend some workarounds?

**Comment by victorkitov** [comment]
Under pytorch 0.4.1 everything runs without problems.

**Comment by zdgithub** [comment]
Yes, I solved it by
`conda install pytorch=0.4.1`
`conda install pillow torchvision scipy`
