### ISSUE TITLE
models given don't work on Windows

### ISSUE THREAD

**Issue by jnnnnn** [sunshineatnoon/PytorchWCT#2]
[Torch binary serialization is platform-dependent](https://github.com/torch/torch7/blob/master/doc/serialization.md) which means that the given models don't work in Windows.

**Comment by sunshineatnoon** [comment]
Hi, I haven't tried to run torch/pytorch on Windows, maybe you can ask on [Pytorch Forum](.https://discuss.pytorch.org/) or [Torch Googlegroup](https://groups.google.com/forum/#!forum/torch7).

**Comment by Redoykhan555** [comment]
Get hold of a linux machine, use [this code](https://github.com/clcarwin/convert_torch_to_pytorch) to convert to .pth files. Use them.

**Comment by inmchoi** [comment]
use pytorch 0.4 version (torch legacy + serialization load lua function) and from utill.py, add argument on load_lua such as  
vgg1 = load_lua(args.vgg1,long_size=8) because window is reading it as 4 bit

on my utill.py
class WCT(nn.Module):
    def __init__(self,args):
        super(WCT, self).__init__()

        # load pre-trained network
         vgg1 = load_lua(args.vgg1,long_size=8)
        decoder1_torch = load_lua(args.decoder1,long_size=8)
        vgg2 = load_lua(args.vgg2,long_size=8)
        decoder2_torch = load_lua(args.decoder2,long_size=8)
        vgg3 = load_lua(args.vgg3,long_size=8)
        decoder3_torch = load_lua(args.decoder3,long_size=8)
        vgg4 = load_lua(args.vgg4,long_size=8)
        decoder4_torch = load_lua(args.decoder4,long_size=8)
        vgg5 = load_lua(args.vgg5,long_size=8)
        decoder5_torch = load_lua(args.decoder5,long_size=8)
