### ISSUE TITLE
about the log(Ls) in Table 2

### ISSUE THREAD

**Issue by hello-trouble** [sunshineatnoon/PytorchWCT#21]
So sorry to bother you .  I have a little bit of trouble calculating the   log(Ls) of various methods in Table 2. The logarithm of the loss with covariance matrix is always negative, and the absolute value is greatly different from the paper. Would it be possible for you to share the evaluation code you used to computer the log(Ls) in the Table 2?  Thank you very much for your help.

**Comment by sunshineatnoon** [comment]
Sorry, I'm not an author of this paper. Please contact the authors for your questions about the paper.
