### ISSUE TITLE
Using higher version pytorch

### ISSUE THREAD

**Issue by LiewFeng** [sunshineatnoon/PytorchWCT#22]
@sunshineatnoon Thank you for your pytorch implementation.
I'm using pytorch 1.3.1, which will get the following error:
`Traceback (most recent call last):
  File "WCT.py", line 9, in <module>
    from util import *
  File "/userhome/PytorchWCT/util.py", line 3, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'`
Then I install [torchfile](https://github.com/bshillingford/python-torchfile), and replace `from torch.utils.serialization import load_lua` with `import torchfile`, replace `load_lua` with `torch.load`. I encounter another problem:
`Traceback (most recent call last):
  File "WCT.py", line 49, in <module>
    wct = WCT(args)
  File "/userhome/PytorchWCT/util.py", line 33, in __init__
    self.e1 = encoder1(vgg1)
  File "/userhome/PytorchWCT/modelsNIPS.py", line 11, in __init__
    self.conv1.weight = torch.nn.Parameter(vgg1.get(0).weight.float())
TypeError: 'NoneType' object is not callable`
Could you help me? Lots of thanks!

**Comment by LiewFeng** [comment]
Fixed.

**Comment by moonmoonCL** [comment]
I meet the same problem，
How did you solve it？
Thanks！

**Comment by jeonghomin** [comment]
> Fixed.

can you share how you solved this problem . im stuck in issues while changing it to torchfile
