### ISSUE TITLE
About the speed

### ISSUE THREAD

**Issue by LiewFeng** [sunshineatnoon/PytorchWCT#23]
@ccrome @sunshineatnoon Thank you for your code. I have a question about the speed.
According to the [paper](https://arxiv.org/pdf/1705.08086.pdf), for 256*256 pictures, the speed should be 0.83s/image.
I set `--fineSize` to be 256 and used gpu, but I got a much slower speed, 28s/image, as the following:

`Transferring in4.jpg
Elapsed time is: 31.397334
Transferring in3.jpg
Elapsed time is: 26.311115
Transferring in1.jpg
Elapsed time is: 29.399027
Transferring in2.jpg
Elapsed time is: 27.614766
Processed 4 images. Averaged time is 28.680560`

Is it normal? Or there is something wrong with me?

**Comment by sunshineatnoon** [comment]
I don't think that's normal. Average time should be about 1 second for 512 images
