### ISSUE TITLE
About batch size

### ISSUE THREAD

**Issue by oldfemalepig** [sunshineatnoon/PytorchWCT#24]
Hello. Thank you very much for your work. I find that in the inference process, WCT transformation is carried out when batch size is 1. Can it be carried out when batch size is not 1?

**Comment by sunshineatnoon** [comment]
I think you can modify the code for larger batch size. But at some point, you still need a [for loop](https://github.com/sunshineatnoon/PytorchWCT/blob/master/util.py#L53) to threshold the decomposed matrices.
