### ISSUE TITLE
GPU memory requirements

### ISSUE THREAD

**Issue by thiagolcks** [sunshineatnoon/PytorchWCT#3]
Hi!

I'm trying to run the code with the default images but I'm getting this error:

```
RuntimeError: cuda runtime error (2) : out of memory
```

I'm running it on a 1080 ti (11GB). Do you know what the GPU memory requirements are?

**Comment by sunshineatnoon** [comment]
It needs at most 4GB on GPU.

**Comment by thiagolcks** [comment]
Humm.... any idea why I could be getting this error? It's happening right after running the code.

**Comment by sunshineatnoon** [comment]
Can u run other pytorch programs with GPU?

**Comment by ccrome** [comment]
How much memory on your CPU?

**Comment by maciej3031** [comment]
Try to change:
`csF = Variable(csF)`
to:
`csF = Variable(csF, volatile=True)`
in WCT.py line 93. It helped for me.
