### ISSUE TITLE
Why Im5 is not used in styleTransfer ?

### ISSUE THREAD

**Issue by edwin0cheng** [sunshineatnoon/PytorchWCT#6]
`def styleTransfer(contentImg,styleImg,imname,csF):

    sF5 = wct.e5(styleImg)
    cF5 = wct.e5(contentImg)
    sF5 = sF5.data.cpu().squeeze(0)
    cF5 = cF5.data.cpu().squeeze(0)
    csF5 = wct.transform(cF5,sF5,csF,args.alpha)
    Im5 = wct.d5(csF5)

    sF4 = wct.e4(styleImg)
    cF4 = wct.e4(contentImg)  <---- This should be Im5 ?
    sF4 = sF4.data.cpu().squeeze(0)
    cF4 = cF4.data.cpu().squeeze(0)
    csF4 = wct.transform(cF4,sF4,csF,args.alpha)
    Im4 = wct.d4(csF4)`

**Comment by sunshineatnoon** [comment]
Because Im4 gives visually better results. Of course you can use Im5 too.
